packages:
  # all packages in direct subdirs of packages/
  - 'packages/*'
  # all packages in subdirs of apps/
  - 'apps/*'
catalog:
  tailwind-merge: ^2.5.2
  tailwindcss: ^3.4.10
  tailwindcss-3d: ^1.0.7
  tailwindcss-animate: ^1.0.7
  postcss: ^8.4.44
  postcss-scss: ^4.0.3
  postcss-syntax: ^0.36.2
  postcss-nested: ^6.2.0
  autoprefixer: ^10.4.20
